from __future__ import annotations

from typing import Any


MCP_CATALOG: list[dict[str, Any]] = [
    {
        "id": "github",
        "name": "GitHub",
        "description": "Repositories, issues, pull requests, Actions and code search.",
        "transport": "stdio",
        "command": "docker",
        "args": ["run", "-i", "--rm", "-e", "GITHUB_PERSONAL_ACCESS_TOKEN", "ghcr.io/github/github-mcp-server"],
        "secret_name": "GITHUB_PERSONAL_ACCESS_TOKEN",
        "risk": "write",
        "official": True,
    },
    {
        "id": "filesystem",
        "name": "Filesystem",
        "description": "Read and manage files inside explicitly allowed directories.",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-filesystem"],
        "secret_name": None,
        "risk": "write",
        "official": True,
    },
    {
        "id": "postgres",
        "name": "PostgreSQL",
        "description": "Inspect schemas and query a PostgreSQL database.",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-postgres"],
        "secret_name": "DATABASE_URL",
        "risk": "data",
        "official": True,
    },
    {
        "id": "fetch",
        "name": "Web Fetch",
        "description": "Fetch web pages and convert them into model-friendly content.",
        "transport": "stdio",
        "command": "uvx",
        "args": ["mcp-server-fetch"],
        "secret_name": None,
        "risk": "read",
        "official": True,
    },
    {
        "id": "brave-search",
        "name": "Brave Search",
        "description": "Web and local search through Brave Search API.",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-brave-search"],
        "secret_name": "BRAVE_API_KEY",
        "risk": "read",
        "official": False,
    },
    {
        "id": "slack",
        "name": "Slack",
        "description": "Search channels and read or send workspace messages.",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-slack"],
        "secret_name": "SLACK_BOT_TOKEN",
        "risk": "write",
        "official": False,
    },
    {
        "id": "notion",
        "name": "Notion",
        "description": "Read, search and update Notion pages and databases.",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@notionhq/notion-mcp-server"],
        "secret_name": "NOTION_TOKEN",
        "risk": "write",
        "official": True,
    },
    {
        "id": "google-drive",
        "name": "Google Drive",
        "description": "Search and read documents stored in Google Drive.",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-gdrive"],
        "secret_name": "GDRIVE_CREDENTIALS",
        "risk": "data",
        "official": False,
    },
    {
        "id": "memory",
        "name": "Knowledge Graph",
        "description": "Persistent entity and relationship memory for agents.",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-memory"],
        "secret_name": None,
        "risk": "write",
        "official": True,
    },
]


def find_mcp_preset(preset_id: str) -> dict[str, Any] | None:
    return next((item for item in MCP_CATALOG if item["id"] == preset_id), None)
