"""memory notes

Revision ID: 568bc446df4d
Revises: 58006f1b8b66
Create Date: 2026-07-28 22:42:21.061376
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '568bc446df4d'
down_revision: Union[str, Sequence[str], None] = '58006f1b8b66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('scope', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('links', sa.JSON(), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'scope', 'run_id', name='uq_memory_scope_run')
    )
    op.create_index(op.f('ix_memory_notes_run_id'), 'memory_notes', ['run_id'], unique=False)
    op.create_index(op.f('ix_memory_notes_workspace_id'), 'memory_notes', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_notes_workspace_id'), table_name='memory_notes')
    op.drop_index(op.f('ix_memory_notes_run_id'), table_name='memory_notes')
    op.drop_table('memory_notes')
    # ### end Alembic commands ###

